version: '3.8'

services:
  pwm_server:
    image: pwm
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 2024:2024
    command: ['node', '--inspect=0.0.0.0:9229', 'index.js']
